# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

# eg: "group-a, group-b, group1, group2"

default_platform(:android)

platform :android do
  desc "Distribute Android app
  lane :test do
    output_pattern = 'app/build/test-results/testDebugUnitTest/TEST-*.xml'
    
    # We ignore exit code otherwise we wouldn't get to the actions below on test failure
    gradle(task: "testDebugUnitTest")

    pretty_junit(file_pattern: output_pattern)
  end
end
